### PR TITLE
Add Term type constructor, fix for/all

### LINKED ISSUE #12: Unsoundness from for/all
In this program:
```
(: f : (C→ PosInt PosInt))
(define (f x)
  (for/all ([y x])
    (expect-concrete y)))

(define-symbolic symb-x integer?)
(f (assert-type symb-x : PosInt))
```
The `for/all` takes away the `U` from `PosInt` and binds `y` with type `CPosInt`, even though at run time it's bound to a symbolic constant `symb-x`.

### PR DESCRIPTION
**Pull request by AlexKnauth**
Fixes #12.

### CODE REVIEW

**Comment by AlexKnauth** [comment]
@stchang What do you think of the changes?

The `Term` constructor only accepts solvable types like `CInt`, `CNum`, `CBool`, `CBV`, and `(C-> A ... B)` (where the `A`s and `B` are solvable non-function types).

The `U` constructor flattens inner unions but leaves `Term`s as they are.

The `type-merge` function is what deals with single-shape types, which can be base types like `CInt` and `CBool`, or constructed types like `(CList Any ...)`. All single-shape base types must be solvable, but single-shape constructed types will not be. 

If two types are subtypes of the same single-shape base type, then they are solvable, and they can be merged as a `Term` of the concrete union of the types. If they have the same single-shape list type, then it doesn't create either a `Term` or `U` on the outside, but merges within each element.

Otherwise `type-merge` has to put a `U` on the outside. Within that there are cases where it needs to put both a `U` and a `Term`.

For the mutable positions like `box`, `vector`, and `let #:mutable` I make sure that it can hold values that are the result of merging by using `type-merge` on the type and itself. Just being symbolic isn't enough.

**Comment by stchang** [comment]
Looks ok. One thought I had was, what if we had `U` call `type-merge` while flattening? Would that make things easier or more complicated?

Also, more (new) tests please! For example, you might want to add the code from Sec8 of the guide.

**Comment by AlexKnauth** [comment]
No, I don't think `U` should call `type-merge`. There are times where there should be a `U` type where merging could produce a term. For example with two BVs, if it is known that they have different sizes then it should be a `U` of `CBV`, but a type-merge would produce a `U` of `Term` of `CBV`.

**Comment by AlexKnauth** [comment]
Why? This doesn't really have much to do with unsafe operations. The initial vector examples belong more in `sec3-tests.rkt` since they are safe symbolic effects (I'll add those, they help test merging due to mutation), but the hash examples don't really have anything to do with terms or merging.

**Comment by AlexKnauth** [comment]
What more tests should there be?

**Pull request merged**
