### PR TITLE
Changes needed for Ocelot

### PR DESCRIPTION
**Pull request by AlexKnauth**

### CODE REVIEW

**Comment by stchang** [comment]
Thanks. Would changing `base-forms` to `base/forms` fix the tests?

**Comment by AlexKnauth** [comment]
No, merging https://github.com/stchang/macrotypes/pull/12 would fix them.

**Comment by stchang** [comment]
ok great.

**Comment by stchang** [comment]
So the tests still fail even though https://github.com/stchang/macrotypes/pull/12 is merged. Do you know what the cause is?

**Comment by stchang** [comment]
Also, would you mind adding a line to travis.yml so it clones and tests your typed ocelot repo? Otherwise we're going to get out of sync

**Comment by AlexKnauth** [comment]
The failures in old versions of racket are expected. Typed Rosette relies on a change I made to how generics work (https://github.com/racket/racket/pull/1644), which is currently only there in 6.9 and HEAD. 

The failure on HEAD is weirder. There's just one test that's failing at runtime. It appears to be this one:
https://travis-ci.org/stchang/typed-rosette/jobs/250557454#L621-L627
```racket
(check-type (type-of s) : (C→ Any Bool) -> vector?)
```
```
--------------------
FAILURE
name:       check-equal?
location:   rosette-guide-sec7-tests.rkt:65:0
actual:     vector?
expected:   #<procedure:vector?>
--------------------
```

**Comment by AlexKnauth** [comment]
`vector?` thing fixed now.

**Comment by stchang** [comment]
Hmm, I think the tests ran out of memory? Does ocelot have high requirements?

**Comment by stchang** [comment]
Btw, I'm assuming this pr supercedes #9?

**Comment by stchang** [comment]
Not sure what's going on with the tests. Only suggestion I could find is [trying to reduce number of parallel jobs](https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error).

Can you add `-j 1` or `-j 2` to the line that installs ocelot? Not sure why it matters for ocelot but not others.

**Comment by stchang** [comment]
And if reducing parallel jobs doesnt work, we can try to [increase memory by setting `sudo: required` instead of `sudo: false`](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments) at the top of the script?

**Comment by stchang** [comment]
Or you could give me access to your repo

**Comment by AlexKnauth** [comment]
I added `-j 1` on the install step. I'm not sure whether that's enough or whether I'll have to do the same thing for the raco setup and raco test steps as well...

Also, I have the "Allow edits from maintainers" option turned on.

**Pull request merged**
